# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PostBar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PostBar
   pod 'Masonry'
   pod 'PPNetworkHelper'
   pod 'SDWebImage','4.4.6'
   pod 'MJExtension'
   pod 'WMPageController'
   pod 'TZImagePickerController'
   pod 'RTRootNavigationController'
   

  target 'PostBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostBarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
